//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchMovieTMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMovie
    {
        public int BookingID { get; set; }
        public Nullable<int> userInfoID { get; set; }
        public Nullable<int> Id_Movie { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> totalPayment { get; set; }
        public Nullable<decimal> totalChange { get; set; }
    }
}
