//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchMovieTMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int userInfoID { get; set; }
        public string lastName_Cus { get; set; }
        public string firstName_Cus { get; set; }
        public int phoneNum { get; set; }
        public Nullable<int> userID { get; set; }
        public string email { get; set; }
    
        public virtual User User { get; set; }
    }
}
