//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchMovieTMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BookHistory_User
    {
        public int Booking_ID { get; set; }
        public string Movie { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> Amount_Pay { get; set; }
        public Nullable<decimal> Change { get; set; }
    }
}
