//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchMovieTMS.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserInfo
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Username { get; set; }
        public int Role { get; set; }
        public int Phone_Number { get; set; }
        public string Email { get; set; }
    }
}
